config/routes.rb
Pmcards::Application.routes.draw do
  resources :shopping_cart_items

  get "/designers" => "designers#index", as: :designer_index
  get "designers/:designer_name" => "designers#show", as: :designer_profile
  get "store/index"
  get "/about" => "home#about", as: :about
  get "/contact" => "home#contact", as: :contact
  resources :cards

  devise_for :admins
  devise_for :users

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         # :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cards
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, allow_blank: true, format: {
            with: %r{\.(gif|jpg|png)\Z}i,
            message: 'must be a URL for GIF, JPG or PNG image.'
            }
  validate :card_designer, presence: true

  belongs_to :admin
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :card
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shopping_cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :description, :price, :admin_id)
    end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController

  def index
    @designers = Card.select(:card_designer).distinct(:card_designer).order(:card_designer).map do |dg|
        dg.card_designer
      end
  end

  def show
    @designer_cards = Card.where(card_designer: params[:designer_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @card = Card.all.order({created_at: :desc}).limit(3)
  end

  def about
  end

  def contact
  end
end

app/controllers/shopping_cart_items_controller.rb
class ShoppingCartItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shopping_cart_item, only: [:show, :edit, :update, :destroy]
  before_action :set_card_options

  # GET /shopping_cart_items
  # GET /shopping_cart_items.json
  def index
    @shopping_cart_items = current_user.shopping_cart_items
    
    puts "@shopping_cart_items"
    puts @shopping_cart_items.inspect
    
    puts "current_user"
    puts current_user.inspect
    
    @total_amount = 0
    @shopping_cart_items.each do |shopping_cart_item|      
      puts "total for loop"
      puts shopping_cart_item.quantity * shopping_cart_item.card.price
      @total_amount += shopping_cart_item.quantity * shopping_cart_item.card.price
    end
  end

  # GET /shopping_cart_items/1
  # GET /shopping_cart_items/1.json
  def show
  end

  # GET /shopping_cart_items/new
  def new
    @shopping_cart_item = ShoppingCartItem.new
  end

  # GET /shopping_cart_items/1/edit
  def edit
  end

  # POST /shopping_cart_items
  # POST /shopping_cart_items.json
  def create
    @shopping_cart_item = ShoppingCartItem.new(shopping_cart_item_params)
    @shopping_cart_item.user_id = current_user.id

    respond_to do |format|
      if @shopping_cart_item.save
        format.html { redirect_to @shopping_cart_item, notice: 'Shopping cart item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shopping_cart_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @shopping_cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_cart_items/1
  # PATCH/PUT /shopping_cart_items/1.json
  def update
    respond_to do |format|
      if @shopping_cart_item.update(shopping_cart_item_params)
        format.html { redirect_to @shopping_cart_item, notice: 'Shopping cart item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shopping_cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_cart_items/1
  # DELETE /shopping_cart_items/1.json
  def destroy
    @shopping_cart_item.destroy
    respond_to do |format|
      format.html { redirect_to shopping_cart_items_url }
      format.json { head :no_content }
    end
  end

  private
    def set_card_options
      @all_card_options = Card.all.map{|card| [card.title, card.id] }
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart_item
      @shopping_cart_item = ShoppingCartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_cart_item_params
      params.require(:shopping_cart_item).permit(:user_id, :card_id, :quantity)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @cards = Card.order(:price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/designer_helper.rb
module DesignerHelper
end

app/helpers/shopping_cart_items_helper.rb
module ShoppingCartItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :card_designer %><br>
    <%= f.text_field :card_designer %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>
  <table>
    <% @cards.each do |card| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(card.image_url, class: 'list_image') %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= card.title %></dt>
            <dd><%= truncate(strip_tags(card.description), length: 80) %></dd>
            <dd><%= card.card_designer %></dd>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', card %><br/>
          <%= link_to 'Edit', edit_card_path(card) %><br/>
           <td><%= button_tag 'Delete', class: "btn btn-sm btn-danger btn-delete-card", href: card_path(card) %></td>
        </td>
      </tr>
    <% end %>
  </table>
<br />

<%= link_to 'New card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>

<p>
  <strong>Designer:</strong>
  <%= @card.card_designer %>
</p>

<p>
  <strong>Price:</strong>
  <%= @card.price %>
</p>

<!-- <p>
  <strong>Admin:</strong>
  <%= @card.admin_id %>
</p> -->

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/designers/index.html.erb
 <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
    <div class="list-group">
    <% @designers.each do |designer| %>
      <%= link_to designer, designer_profile_path(designer), class: "list-group-item" %>
      <% end %>
    </div>
  </div><!--/span-->

app/views/designers/show.html.erb
<h1>Designer <%= params[:designer_name] %></h1>
<div class="row">     
  <% @designer_cards.each do |card| %>
  <div class="col-6 col-sm-6 col-lg-4 text-center">
    <%= image_tag(card.image_url) %>
    <h2><%= card.title %></h2>
    <p><%= truncate(strip_tags(card.description), length: 80) %></p>
    <p><%= card.card_designer %></p>
    <p><%= card.price %></p>
    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
  </div>
    <% end %>   
</div>

app/views/home/about.html.erb
<h1>Coming Soon</h1>

app/views/home/contact.html.erb
<h1>Coming Soon</h1>

app/views/home/designer.html.erb
<h1>Coming Soon</h1>

app/views/home/index.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <div class="container">
    <h1>Hello, world!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <b><%= link_to 'Check our products', store_index_path, class: "btn btn-sm btn-primary btn-check" %></b>
  </div>
</div>


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">
  <h1> New Arrival </h1>
  <hr>
<!-- Three columns of text below the carousel -->
<div class="row">
  <% @card.each do |card| %>
  <div class="col-lg-4">
    <%= image_tag(card.image_url) %>
    <h2><%= card.title %></h2>
    <p><%= truncate(strip_tags(card.description), length: 80) %></p>
    <p><%= card.card_designer %></p>
    <p><%= card.price %></p>
    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
  </div><!-- /.col-lg-4 -->
 <% end %>
</div><!-- /.row -->

<!-- START THE FEATURETTES -->
<hr>

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-5">
    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SophLove Cards Onlie Store</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class='<%= controller.controller_name %>'>
     <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">SophLove Cards</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Home", root_path %></li>
                <li><%= link_to "Our Online Store", about_path %></li>
                <li><%= link_to "Our Designers", designer_index_path %></li>
                <li><%= link_to "Contact", contact_path %></li>     
                <% if current_admin %>
                  <li><%= link_to "Admin Sign Out", destroy_admin_session_path, method: :delete %></li>
                <% elsif current_user %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> My SophLove <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="#"> My Orders </a></li>
                        <li><a href="#"> My Favourites </a></li>
                        <li><%= link_to "My Shopping Cart", shopping_cart_items_path %></li>
                      </ul>
                    </a>
                  </li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Sign In <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Sign In", new_user_session_path %></li>
                        <li><%= link_to "No Account yet ?", new_user_registration_path %></li>
                      </ul>
                  </li>
                <% end %>          
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <%= yield %>

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2013 Company, Inc. &middot; </p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/shopping_cart_items/_form.html.erb
<%= form_for(@shopping_cart_item) do |f| %>
  <% if @shopping_cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_cart_item.errors.count, "error") %> prohibited this shopping_cart_item from being saved:</h2>

      <ul>
      <% @shopping_cart_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_id %><br>
    <%= f.select :card_id, @all_card_options %>
  </div>
  
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_cart_items/edit.html.erb
<h1>Editing shopping_cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_cart_item %> |
<%= link_to 'Back', shopping_cart_items_path %>

app/views/shopping_cart_items/index.html.erb
<h1>Listing shopping_cart_items</h1>

<p>Total Amount: <%= @total_amount %></p>

<table>
  <thead>
    <tr>
      <th>Card</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_cart_items.each do |shopping_cart_item| %>
      <tr>
        <td><%= shopping_cart_item.card_id %></td>
        <td><%= shopping_cart_item.quantity %></td>
        <td><%= link_to 'Show', shopping_cart_item %></td>
        <td><%= link_to 'Edit', edit_shopping_cart_item_path(shopping_cart_item) %></td>
        <td><%= link_to 'Destroy', shopping_cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping cart item', new_shopping_cart_item_path %>

app/views/shopping_cart_items/new.html.erb
<h1>New shopping_cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_cart_items_path %>

app/views/shopping_cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @shopping_cart_item.user_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @shopping_cart_item.card_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @shopping_cart_item.quantity %>
</p>

<%= link_to 'Edit', edit_shopping_cart_item_path(@shopping_cart_item) %> |
<%= link_to 'Back', shopping_cart_items_path %>

app/views/store/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1>Our Catalog</h1>
  <% @cards.each do |card| %>
    <div class="entry">
      <%= image_tag(card.image_url) %>
      <h3><%= card.title %></h3>
      <p><%= sanitize(card.description) %></p>
      <p><%= card.card_designer %> </p>
      <div class="price_line">
        <span class="price"><%= card.price %></span>
      </div>
    </div>
  <% end %>